image: alpine/edge
secrets:
  - e9000e44-8b2a-453c-b841-ac28a0688a21
environment:
  REPO: nvim
  GH_USER: tjex
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "git@github.com:/${GH_USER}/${REPO}.git"

